version: '3'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 54325:5432
    environment:
      POSTGRES_DB: mysite
      POSTGRES_USER: django
      POSTGRES_PASSWORD: qwerty
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data

  backend:
    build:
      context: ./mysite
    privileged: true
    restart: always
    expose:
      - 8000
    command: bash -c "
      python manage.py migrate &&
      gunicorn mysite.wsgi -b 0.0.0.0:8000
      "
    environment:
      DJANGO_SETTINGS_MODULE: mysite.settings.site_1

  nginx:
    build:

