# Generated by Django 4.0.4 on 2022-05-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=16, verbose_name='имя')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
            ],
        ),
    ]
