# Generated by Django 4.0.4 on 2022-06-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mainapp', '0002_productcategory_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
